export const DISTORTION_MIN_DISTORTION = 0
export const DISTORTION_MAX_DISTORTION = 1
export const DISTORTION_DEFAULT_DISTORTION = 0.5

export const DISTORTION_MIN_WET = 0
export const DISTORTION_MAX_WET = 1
export const DISTORTION_DEFAULT_WET = 0.5